apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
#  no necessary namespace
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /work